site_name: My Docs API Documentation
site_description: Учебный сайт с документацией API, опубликованный через GitHub Pages.
theme: material

nav:
  - Home: index.md
  - About: about.md
  - Reference API: reference_api.md